CREATE TABLE memo(
	`memo_id`	VARCHAR(6)	NOT NULL	PRIMARY KEY,
	`user_id`	INTEGER			NOT NULL,
	title	VARCHAR(128)NOT NULL,
	`content_json`	JSON,
	`content_html`	TEXT,
	`is_published`	BOOLEAN	NOT NULL,
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	ON UPDATE CURRENT_TIMESTAMP
);